name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Build Docker Image
      run: docker build -t teokarakashev/classwork-1:latest .

    - name: Push Docker Image
      run: docker push teokarakashev/classwork-1:latest
